import type { OfficeContactsSnapshot } from "@diarydock/office";

export const officeContactsPreview: OfficeContactsSnapshot = {
  schemaVersion: 1,
  revision: "2026-09-04T09:00:00.000Z",
  contacts: [
    {
      contentComplete: true,
      id: "contact-solicitor",
      firstName: "Priya",
      lastName: "Shah",
      role: "Family solicitor",
      company: "Shah & Moss",
      category: "Legal",
      phone: "020 7946 0123",
      email: "priya@example.test",
      address: "10 Market Square, London",
      notes: "Primary contact for wills and lasting power of attorney.",
      isFavourite: true,
      isEmergencyContact: true,
      nextReviewDate: "2027-03-12",
      linkedDocumentIds: [],
      linkedPolicyIds: [],
      linkedContractIds: [],
      linkedBillIds: [],
      contactNotes: [{
        id: "note-solicitor",
        note: "Confirmed the annual document review process.",
        createdAt: "2026-09-02T09:15:00.000Z",
      }],
      meetings: [{
        id: "meeting-solicitor",
        title: "Annual estate review",
        date: "2026-10-08",
        time: "10:30",
        notes: "Bring the current will summary.",
        completed: false,
        createdAt: "2026-09-02T09:00:00.000Z",
      }],
      createdAt: "2025-03-12T09:00:00.000Z",
      updatedAt: "2026-09-02T09:15:00.000Z",
    },
    {
      contentComplete: true,
      id: "contact-adviser",
      firstName: "Daniel",
      lastName: "Reed",
      role: "Financial adviser",
      company: "Reed Planning",
      category: "Financial",
      phone: "020 7946 0456",
      email: "daniel@example.test",
      address: "",
      notes: "",
      isFavourite: false,
      isEmergencyContact: false,
      nextReviewDate: "2027-01-15",
      linkedDocumentIds: [],
      linkedPolicyIds: ["life-policy"],
      linkedContractIds: [],
      linkedBillIds: [],
      contactNotes: [],
      meetings: [],
      createdAt: "2024-01-15T09:00:00.000Z",
      updatedAt: "2026-08-20T11:00:00.000Z",
    },
  ],
};
