import type { GardenSection, GardenSectionId } from "./types.ts";

export const gardenSections: GardenSection[] = [
  {
    id: "pets",
    title: "Pets",
    description:
      "Keep pet profiles, health records, routines and care information together.",
    icon: "heart",
    scope: ["Profiles", "Appointments", "Care routines", "Documents"],
    documentTerms: ["pet", "vet", "veterinary", "vaccination", "microchip"],
    reminderTerms: ["pet", "vet", "vaccination", "flea", "worm"],
  },
  {
    id: "outdoor-spaces",
    title: "Outdoor Spaces",
    description: "Organise outdoor areas, boundaries, gates and safety notes.",
    icon: "sun",
    scope: ["Areas", "Photos", "Boundaries", "Safety notes"],
    documentTerms: [
      "garden",
      "patio",
      "balcony",
      "outdoor",
      "deck",
      "lawn",
      "planting",
      "boundary",
      "fence",
      "gate",
      "wall",
      "safety",
      "outdoor light",
      "neighbour",
    ],
    reminderTerms: [
      "garden",
      "patio",
      "balcony",
      "outdoor",
      "lawn",
      "planting",
      "boundary",
      "fence",
      "gate",
      "wall",
      "safety",
      "outdoor light",
    ],
  },
  {
    id: "jobs",
    title: "Garden Jobs",
    description: "Track maintenance, seasonal work and outdoor projects.",
    icon: "calendar",
    scope: ["Tasks", "Projects", "Seasonal work", "History"],
    documentTerms: [
      "garden",
      "outdoor",
      "maintenance",
      "repair",
      "hedge",
      "lawn",
      "sprinkler",
      "garden project",
      "landscaping",
      "quote",
      "outdoor project",
      "planting plan",
    ],
    reminderTerms: [
      "garden",
      "outdoor",
      "maintenance",
      "repair",
      "hedge",
      "lawn",
      "sprinkler",
      "garden project",
      "landscaping",
      "quote",
      "outdoor project",
      "planting plan",
    ],
  },
  {
    id: "tools-shed",
    title: "Tools & Shed",
    description:
      "Keep shed, greenhouse, tool, machinery and equipment records together.",
    icon: "home",
    scope: ["Sheds", "Tools", "Equipment", "Manuals"],
    documentTerms: [
      "shed",
      "greenhouse",
      "outbuilding",
      "garden office",
      "summer house",
      "tool",
      "equipment",
      "lawnmower",
      "mower",
      "pressure washer",
      "strimmer",
      "warranty",
      "manual",
    ],
    reminderTerms: [
      "shed",
      "greenhouse",
      "outbuilding",
      "garden office",
      "summer house",
      "tool",
      "equipment",
      "lawnmower",
      "mower",
      "pressure washer",
      "strimmer",
      "battery",
    ],
  },
  {
    id: "bins",
    title: "Bins & Collections",
    description: "Keep waste, recycling and collection dates easy to remember.",
    icon: "archive",
    scope: ["Schedules", "Waste types", "Changes", "Reminders"],
    documentTerms: [
      "bin",
      "bins",
      "recycling",
      "waste",
      "collection",
      "council",
    ],
    reminderTerms: [
      "bin",
      "bins",
      "recycling",
      "waste",
      "collection",
      "garden waste",
    ],
  },
];

export function isGardenSection(value: string): value is GardenSectionId {
  return gardenSections.some((section) => section.id === value);
}

export function getGardenSection(value: GardenSectionId) {
  return gardenSections.find((section) => section.id === value)!;
}
