import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const a = "11111111-1111-4111-8111-111111111111";
const b = "22222222-2222-4222-8222-222222222222";
test("recap schedule isolates users, respects zones/DST, deduplicates and expires missed alerts", async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role;
      create schema auth; create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql as $$ select current_setting('request.uid',true)::uuid $$;
      create function auth.role() returns text language sql as $$ select current_setting('request.role',true) $$;
      grant usage on schema auth to authenticated;
      create function recap_clock() returns timestamptz language sql as $$ select current_setting('test.clock')::timestamptz $$;
      select set_config('test.clock','2026-09-12T06:00:00Z',false);
      select set_config('request.role','service_role',false);
    `);
    // Inject a deterministic clock into the exact production SQL for schedule tests.
    const sql = await readFile(new URL("../supabase/migrations/20260912190000_recaps.sql",import.meta.url),"utf8");
    await db.exec(sql.replaceAll("now()","public.recap_clock()"));
    const times = await readFile(new URL("../supabase/migrations/20260912203000_recap_times.sql",import.meta.url),"utf8");
    await db.exec(times.replaceAll("now()","public.recap_clock()"));
    await db.query("insert into auth.users values($1),($2)",[a,b]);
    await db.query("insert into appointment_devices(id,user_id,platform,token,updated_at) values($1,$1,'ios',repeat('a',64),public.recap_clock()),($2,$2,'ios',repeat('b',64),public.recap_clock())",[a,b]);
    await db.query("insert into recap_preferences(user_id,daily,weekly,push) values($1,true,true,true),($2,false,false,false)",[a,b]);
    const clock = (v:string)=>db.query("select set_config('test.clock',$1,false)",[v]);
    const claim = ()=>db.query<{id:string;kind:string;user_id:string}>("select * from claim_recap_notifications()");
    await clock("2026-09-12T06:59:00Z"); assert.equal((await claim()).rows.length,0);
    await clock("2026-09-12T07:00:00Z");
    const first = (await claim()).rows; assert.equal(first.length,1); assert.equal(first[0]!.kind,"daily"); assert.equal(first[0]!.user_id,a);
    assert.equal((await claim()).rows.length,0);
    await db.exec("update recap_notifications set status='sent',lease_until=null");
    assert.equal((await claim()).rows.length,0,"sent messages cannot be requeued");
    await clock("2026-09-13T07:00:00Z"); assert.equal((await claim()).rows[0]!.kind,"daily");
    await clock("2026-09-13T19:00:00Z"); assert.equal((await claim()).rows[0]!.kind,"weekly");
    await db.exec("update recap_notifications set status='sent',lease_until=null");
    await clock("2026-10-25T07:59:00Z"); assert.equal((await claim()).rows.length,0,"winter 8am has not arrived");
    await clock("2026-10-25T08:00:00Z"); assert.equal((await claim()).rows[0]!.kind,"daily");
    await clock("2026-10-25T11:00:00Z"); assert.equal((await claim()).rows.length,0,"stale alerts expire rather than arrive at lunchtime");
    await clock("2026-10-26T07:00:00Z");
    await db.query("update recap_preferences set time_zone='America/New_York' where user_id=$1",[a]);
    await clock("2026-10-26T11:59:00Z"); assert.equal((await claim()).rows.length,0);
    await clock("2026-10-26T12:00:00Z"); assert.equal((await claim()).rows[0]!.kind,"daily");
    await clock("2026-10-27T08:00:00Z");
    await db.query("update recap_preferences set daily_time='23:30',weekly_time='23:45' where user_id=$1",[a]);
    await clock("2026-10-28T04:00:00Z");
    const midnight = (await claim()).rows; assert.equal(midnight.length,1,"23:30 alert can retry after local midnight");
    assert.equal((await claim()).rows.length,0,"a lease prevents duplicate delivery");
    await db.query("update recap_preferences set daily_time='06:45' where user_id=$1",[a]);
    assert.equal((await claim()).rows.length,0,"changing time cancels old queued work");
    await clock("2026-10-28T10:45:00Z"); assert.equal((await claim()).rows[0]!.kind,"daily");
    await clock("2026-11-02T05:00:00Z");
    assert.equal((await claim()).rows[0]!.kind,"weekly","Sunday late-night recap retries on Monday after midnight");
    await assert.rejects(db.query("update recap_preferences set daily_time='24:00' where user_id=$1",[a]));
    await db.exec("set role authenticated");
    await db.query("select set_config('request.uid',$1,false)",[b]);
    assert.equal((await db.query("select * from recap_preferences")).rows.length,1);
    assert.equal((await db.query("update recap_preferences set daily=false where user_id=$1 returning *",[a])).rows.length,0);
    await assert.rejects(db.query("insert into recap_preferences(user_id) values($1)",[a]));
    await assert.rejects(db.query("select * from recap_notifications"));
    await assert.rejects(claim());
    await db.exec("reset role");
    await assert.rejects(db.query("update recap_preferences set time_zone='Invalid/Zone' where user_id=$1",[a]),/Invalid time zone/);
    await db.exec("delete from appointment_devices; delete from auth.users");
    assert.equal((await db.query("select * from recap_preferences")).rows.length,0);
    assert.equal((await db.query("select * from recap_notifications")).rows.length,0);
  } finally { await db.close(); }
});
