import type { KitchenRecipe } from "./planning-types.ts";

export const smartStarterRecipes: KitchenRecipe[] = [
  {
    contentComplete: true,
    id: "diarydock-starter-salmon-traybake",
    version: 1,
    name: "Lemon herb salmon traybake",
    time: "35 min",
    servings: 4,
    image: "",
    ingredients: ["4 salmon fillets", "750g baby potatoes", "300g green beans", "1 lemon"],
    instructions: "Roast the potatoes, add the salmon and beans, then finish with lemon and herbs.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-garden-pasta",
    version: 1,
    name: "Garden vegetable pasta",
    time: "25 min",
    servings: 4,
    image: "",
    ingredients: ["400g pasta", "2 courgettes", "250g cherry tomatoes", "60g parmesan"],
    instructions: "Cook the pasta, soften the vegetables and toss everything together with parmesan.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-chicken-fajitas",
    version: 1,
    name: "Chicken fajita bowls",
    time: "30 min",
    servings: 4,
    image: "",
    ingredients: ["500g chicken breast", "3 peppers", "1 red onion", "300g rice", "1 lime"],
    instructions: "Cook the seasoned chicken and vegetables, then serve over rice with lime.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-chickpea-curry",
    version: 1,
    name: "Creamy chickpea curry",
    time: "30 min",
    servings: 4,
    image: "",
    ingredients: ["2 tins chickpeas", "400ml coconut milk", "200g spinach", "300g rice"],
    instructions: "Simmer the chickpeas in the curry sauce, stir in spinach and serve with rice.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-air-fryer-chicken",
    version: 1,
    name: "Air fryer chicken and wedges",
    time: "35 min",
    servings: 4,
    image: "",
    ingredients: ["600g chicken thighs", "800g potatoes", "2 tsp paprika", "200g salad leaves"],
    instructions: "Air fry the seasoned wedges and chicken until crisp, then serve with salad.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-slow-cooker-stew",
    version: 1,
    name: "Slow cooker beef stew",
    time: "6 hr",
    servings: 4,
    image: "",
    ingredients: ["600g stewing beef", "500g potatoes", "3 carrots", "500ml beef stock"],
    instructions: "Add everything to the slow cooker and cook until the beef is tender.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
  {
    contentComplete: true,
    id: "diarydock-starter-tomato-soup",
    version: 1,
    name: "Roasted tomato soup",
    time: "40 min",
    servings: 4,
    image: "",
    ingredients: ["800g tomatoes", "1 onion", "2 cloves garlic", "500ml vegetable stock"],
    instructions: "Roast the vegetables, simmer with stock and blend until smooth.",
    steps: [],
    favourite: false,
    source: "diarydock",
    sourceUrl: null,
  },
];
