import {
  Archive,
  Bell,
  BriefcaseBusiness,
  Car,
  DoorOpen,
  Flower2,
  Home,
  KeyRound,
  Landmark,
  Mail,
  ShieldCheck,
  Users,
} from "lucide-react";

export const hotspots = [
  {
    id: "attic",
    name: "Attic",
    href: "/room/attic",
    left: "50%",
    top: "25%",
    icon: Archive,
    status: "secure",
  },
  {
    id: "bedroom",
    name: "Bedroom",
    href: "/room/bedroom",
    left: "22%",
    top: "35%",
    icon: KeyRound,
    status: "secure",
  },
  {
    id: "office",
    name: "Office",
    href: "/room/office",
    left: "76%",
    top: "35%",
    icon: BriefcaseBusiness,
    status: "attention",
    count: 2,
  },
  {
    id: "family-room",
    name: "Family Room",
    href: "/room/family-room",
    left: "21%",
    top: "50%",
    icon: Users,
    status: "secure",
  },
  {
    id: "safe-room",
    name: "Safe Room",
    href: "/room/safe-room",
    left: "50%",
    top: "60%",
    icon: ShieldCheck,
    status: "attention",
    count: 1,
  },
  {
    id: "garage",
    name: "Garage",
    href: "/room/garage",
    left: "78%",
    top: "53%",
    icon: Car,
    status: "secure",
  },
  {
    id: "mailbox",
    name: "Mailbox",
    href: "/mailbox",
    left: "11%",
    top: "78%",
    icon: Mail,
    status: "attention",
    count: 3,
  },
  {
    id: "garden",
    name: "Garden",
    href: "/room/garden",
    left: "18%",
    top: "65%",
    icon: Flower2,
    status: "secure",
  },
  {
    id: "driveway",
    name: "Driveway",
    href: "/room/driveway",
    left: "80%",
    top: "71%",
    icon: DoorOpen,
    status: "secure",
  },
  {
    id: "front-gate",
    name: "Front Gate",
    href: "/settings",
    left: "50%",
    top: "84.5%",
    icon: Home,
    status: "secure",
  },
] as const;

export const roomOptions = [
  { id: "attic", name: "Attic", icon: Archive },
  { id: "bedroom", name: "Bedroom", icon: KeyRound },
  { id: "office", name: "Office", icon: BriefcaseBusiness },
  { id: "family-room", name: "Family Room", icon: Users },
  { id: "safe-room", name: "Safe Room", icon: ShieldCheck },
  { id: "garage", name: "Garage", icon: Car },
  { id: "garden", name: "Garden", icon: Flower2 },
  { id: "driveway", name: "Driveway", icon: DoorOpen },
  { id: "vault", name: "Vault", icon: Landmark },
] as const;

export const rooms = {
  attic: {
    title: "Attic",
    description: "Long-term records, legacy notes, and quiet storage for documents you rarely need but never want to lose.",
    documents: ["Birth certificates", "Legacy photo inventory", "Archived tax returns"],
    reminders: ["Review archive box labels in August"],
    actions: ["Upload archive scan", "Share access note", "Mark shelf reviewed"],
  },
  bedroom: {
    title: "Bedroom",
    description: "Personal essentials, identity records, and private instructions kept close at hand.",
    documents: ["Passports", "Marriage certificate", "Personal wishes letter"],
    reminders: ["Passport renewal check due in 42 days"],
    actions: ["Add ID document", "Update private note", "Assign trusted contact"],
  },
  office: {
    title: "Office",
    description: "Work, finance, property, and everyday admin gathered into one focused command room.",
    documents: ["Mortgage statement", "Business insurance", "Accountant contact card"],
    reminders: ["Submit self-assessment prep", "Renew business policy"],
    actions: ["Create finance bundle", "Add account login", "Export advisor pack"],
  },
  "family-room": {
    title: "Family Room",
    description: "Shared family information, care plans, school details, and household continuity notes.",
    documents: ["School contacts", "Care preferences", "Family medical overview"],
    reminders: ["Update emergency contacts next month"],
    actions: ["Invite family member", "Add care note", "Create handover list"],
  },
  "safe-room": {
    title: "Safe Room",
    description: "The protected core for wills, powers of attorney, passwords, and end-of-life instructions.",
    documents: ["Will summary", "Power of attorney", "Password manager recovery"],
    reminders: ["Witness details need confirmation"],
    actions: ["Verify legal contact", "Request signature", "Lock critical files"],
  },
  garage: {
    title: "Garage",
    description: "Vehicles, warranties, tools, and physical assets with values, service dates, and ownership details.",
    documents: ["Car insurance", "MOT certificate", "Tool warranty folder"],
    reminders: ["Book annual service in 18 days"],
    actions: ["Add asset", "Log repair", "Scan warranty"],
  },
  garden: {
    title: "Garden",
    description: "Outdoor assets, pets, maintenance rhythms, and the small recurring tasks that keep home life smooth.",
    documents: ["Garden service contract", "Pet vaccination record", "Outdoor appliance warranty"],
    reminders: ["Schedule tree inspection"],
    actions: ["Add maintenance task", "Save contractor", "Record pet care note"],
  },
  driveway: {
    title: "Driveway",
    description: "Insurance, access, keys, deliveries, and practical household movement in one quick-access place.",
    documents: ["Home insurance", "Spare key locations", "Delivery instructions"],
    reminders: ["Review home cover renewal"],
    actions: ["Add access code", "Update keyholder", "Log delivery preference"],
  },
} as const;

export const vaultItems = [
  { label: "Protected documents", value: "46", icon: Landmark },
  { label: "Trusted contacts", value: "8", icon: Users },
  { label: "Open reminders", value: "12", icon: Bell },
];
